document.getElementById("btn").addEventListener("click", function () {
  console.log("ite");
  document.querySelector("html").className = "old";
  document.querySelector("#p1").textContent =
    "Boat: As you walk nearer to the edge, ocean waves clash into the mixture of sand and dirt that borders the perimeter of the island. Small, orange hermit crabs scurry around the tattered, splintered pieces of Japanese cedar wood that were torn out of the main structural build. Like walking on little pieces of legos, the jagged rocks and honed wood bits struck out from beneath the sand, piercing the bareness of your feet. You climb up the wooden ladder that’s perched on the massive but run-down ship. The frayed, yellow stained sails barely hang onto the high wooden beams and the loudness of the wind that gusts into them is overbearing. The wooden planks creak and tremble with each step taken, almost on the verge of collapsing. You run your fingers through the white outline of the ship, touching unpleasant mold and overwhelming amounts of moss along the way as well. Behind the main beam that centers the ship, a rectangular door that's centered with a circular window leads to the basement of the boat. As you open the door, the sickening stench immediately fills your nostrils and the vicinity. The smell only heightens the deeper you travel into the unlit and humid lower deck. The small circular windows that are evenly spaced apart on both sides of the walls are the only light source. Spiders tickle your feet as you trip over the stacks of pouches filled with rotting food that are years old. Shards of glass from the broken windows, almost invisible to spot, make the floors dangerous to roam around.";
  document.querySelector("#p2").textContent =
    "Village: As you stroll through the barren streets of this once-lively village, a strange feeling of kenopsia washes over you. The wind carries with it a screech from the rusty hinges of the once well kept doors, piercing through the rattling of barren trees which line the outskirts of town. Watch your step as you walk, broken wood planks and shattered glass litter the cobblestone road that could have once been smooth. This town was not burned like Sodom, nor bombed like Warsaw, it suffered a fate much more sinister than the will of one man. Looking into the dirt you may miss the sight of the rusted farming tools that once tilled soil daily. The brown coating of the tools has made them frail and even the thought of touching them might make the handles snap and heads shatter. Grandeur was not thought of when this town was created, the structures could not have reached higher than the trees. The most surprising thing about this city was the lack of life from the ground. You expect ivy lining the walls and birds living in the places where there was once thatch, but none of this is present, and the area stays dead. ";
  document.querySelector("#p3").textContent =
    "Forest: As you walk the uneven path, large blobs of dark greens waver in the wind. Black coffee colored roots uprooted from the dark soil, creating semi circles throughout the ground of dead weeds and dry grass. Patches of moss cover the multiple tree trunks while the dead leaves crunch as you step further into the dark forest. Organ music whistles through the shades of phthalo green leaves with the shivering wind, blown from different directions one minute to the next. The dense air surrounds you as you walk deeper and deeper, following the untidy path. Going under the thick branches, pushing aside the thinner ones sticking in your face, and almost tripping over a tree root, you arrive at a clearing. A clearing of the same dark soil with dead weeds and dry grass. But among those, stood a tree of different shades of pink. Jewels of pink crowed the thick coffee branches that stretch across the sky. With the chilling wind, pedals of pink flutter in the air, twisting and twirling before finally landing. Admiss the pedals’ dance, clashes of metal were heard. Getting closer to the jewel pink tree, you see on one of the thick branches hangs a metal wind chime or what it used to be. With each step you take going closer to it, layers of rust can be seen in patches among the metal. Cracks among the wooden parts holding the metal chimes together, hanging dangerously on a metal line wrapped around the branch.  ";
  document.querySelector("#p4").textContent =
    "Hospital: You explore the island and see a hospital with eroding bricks and muddled windows. You walk in as a rancid smell consumes you. Struggling to breathe, you walk on the sanguine and dirt covered tiles and see the blood covered uniforms of the hospital faculty. You go further into the building and the stench gets stronger, straight ahead you see a bed. The metal bed frame is rusting and you lift up the cover on the bed to see a corpse. The putrid smell of the decaying body almost makes you puke, the mangled pile of flesh just lying there. As part of its skull becomes visible you run away in horror, through the shattered glass on the floor, but can’t seem to find the exit. Small details begin to make themselves visible, such as the scattered rusting tools and the machines having their wires pulled out. As you venture deeper into the hellish cemetery you notice a door with the sign ‘staff only’ on it. Desensitized to the horrors, you walk in to discover a morbid mountain of cadaver, barely resembling the individuals they once represented. The realization dawns upon you that a plague has overrun this hospital. Leaving you with only one option, to escape.";
  document.querySelector("#p5").textContent =
    "Castle: The feeling of the structure intermediate to the island was grandiose. Its colossal size was the first thing apparent to you, and was clad with ruin and nature. Walking closer, the structure of a castle becomes clear. The grass you step on is fragile and dry, akin to the village’s wood and structures, akin to the decaying bones at the boat. At the staircase, the capstones remain sturdy, although the overgrowth of flowers and grass cover them. Inside, the darkness of the structure contrasted the cascading light of the sun. The vines overtaking the castle bore grapes. The doves and lambs fled in your presence, and sharp snapping of dry grass constantly rings in your ear. It is funny, even though the bustling nature of the structure has long died, in a way, it became more alive than ever. You pick up a rusting iron sword whose handle became essentially green. The sun-baked vegetation extended upwards to the summit of the structure. The constant clatter of the insects and animals adjoined to the scenery. It was peaceful, you could see most of the island from the structure’s rooftop.";
  document.querySelector("#p6").textContent =
    "Cliff: As you walk towards the cliff, you see a wooden entrance gate that leads to the top. The wood material of the door was rotten and chipped as the color and decorations of the door faded. The closer you walk to the door, the older the island seems to be. There was a beautiful but old sakura tree; it seemed to be the only thing worthy of looking at at the bottom of the cliff. The eerie twinkling sound of wind chimes on its branches creates a lonely melody as you make your way up the cliff. The ground was covered with dirt, and the blood stained grass that rustled as the wind blew through them. The smell of clean but suffocating air surrounds you as you travel further up this cliff. At the very top of the cliff you see protective fences, though they were rotten and extremely fragile. From the top you see a vast ocean spreading out into the horizon. The crashing waves sound as if it’s trying to once again bring the lively spirit back to this island. There is a bright moon, somewhat covered by the dark clouds. As you look into a distance, the cold and quiet environment slowly comes to you as the blood on the grass seems to spread. ";
});

document.getElementById("btn2").addEventListener("click", function () {
  console.log("ite");
  document.querySelector("html").className = "new";
  document.querySelector("#p1").textContent =
    "Boat: The crisp, cool air blows gently on the bright white sails that are tightly attached to the wooden beams of the massive Japanese ship. The fresh smell of new Japanese cedar wood fills the air as tourists come to visit this functional build that helped bring many to this island. Although it is at the very edge of this island and can be easily missed, this structure is worth finding as the outer appearance is not the only thing it displays. White borders the outer edges of the ship, giving it a cleaner and fresher look whilst allowing the wood to pop in color. Tourists enter through a sturdy ladder that is propped against the side port side of the boat. Dark oak planks stretch throughout the floors of the upper and lower decks. A rectangular door with a little centered window hides behind the tallest beam of the ship and is the gateway to the stored goods. Dimly lit lanterns are hung orderly around the lower decks but light shines brightly through the small windows scattered evenly throughout the walls. Many tourists who come receive food that is stored in big linen pouches as well as explore the various rooms filled with metal tools, old paintings, and first aid supplies. ";
  document.querySelector("#p2").textContent =
    "Village:  Life flows from the open windows of the joyful cottages that line the road, and music swirls through the wind during festivals. The city center can be heard from miles away, the cheers of children and the laughter of their parents fill the surrounding grove of fruitful trees. Apple baskets lay unattended at the base of the trees, as their owners picnic in the sunlit field on clement days. As you head toward the outskirts of town the smell of mulch and fresh tilled land wafts over from the farms which support the diets of the multitude of people who live and work in the town. Life here is content with its miniature scale, seeing no reason in grand structures or fancy developments. Gardens and vines make it seem that, without tending, nature would take precedence over humanity. In a settlement where everyone contributes to the wellness of others, what will you bring with you when you visit?";
  document.querySelector("#p3").textContent =
    "Forest: Walking down the trail, whispers are heard from the trees, laughter echoes through the woods, and noise sounds from the interaction of shoes and soil. Shades of green cover the sky, lighting up the paths with the sun. The air was clear and as fresh as it could be. As you walk along, people are seen working, conversing and even sleeping under the warm sunlight. Deeper into the forest, gardeners were seen to be tending to plants. Trees were maintained, cut into shape with no branches out of place. Weeds were pulled out of the rich soil, letting the bright green grass have more space. Now laughter and chatter was heard louder and clearer than before, a clearing came into view. Children were running around playing and parents were sitting down on the soft green grass chatting. A pink pedal gently floated down in front of you. Looking up to see where it came from, you saw a large tree colored in shades of pink standing in the middle of everything. The pink pedals continue to fall in the cool air, shining like jewels in the warm sunlight. Stepping closer, melodic chimes were heard. There, on an oak colored branch hung a beautiful traditional wind chime. The metal chimes sparkle in the light rays, not a single speck of dust was seen. Even the wooden piece hung sturdy on the iron wire wrapped around the branch was freshly painted. Life was seen all around. ";
  document.querySelector("#p4").textContent =
    "Hospital: You wander around the island and see a hospital that looks newly renovated. The building is made with clean, freshly painted bricks with glimmering windows to accompany it. You go inside, as you enter the smell of the minty, fresh air envelops you. Inside you see multiple hospital faculty walking around on the sparkling tiles with their patients. You hear the chimes of the automatic door being utilized by the patients and their visitors. All of the furniture, machinery, and tools are in pristine condition. Everything you see is spotless, invoking a safe and cozy feeling. The staff are welcoming and the patients are all seen in a cheery mood. This allures you to continue wandering around the halls of this grandiose building. As you venture deeper through the palace of healing you smell a light floral scent from the vast amount of get well soon flowers. You are in awe of the state of the art technology that is being utilized and the pleasant way that everybody is being treated.";
  document.querySelector("#p5").textContent =
    "Castle: This is the beating heart of the island, the exhibition of decades of human engineering and architecture. You’ll come for its sheer size, but stay for the scenery it provides. The first thing you see as you approach this structure is the staircase leading to its door. It's welcoming, and the sound of the smooth stones compliment your steps as you walk up to the door. The castle is open for everybody to experience, which is why it is always overrun with people. Don’t worry though, the castle's colossal nature gives an inherent spaciousness, if the castle was empty you would hear the echo of your footsteps. Of course, this castle is the political epicenter of the island, however most people forget that. Inside, the fresh coat of lacquer on the mahogany wood shines as bright as the gold and quartz embedded in the floors and walls. The castle houses precious historical artifacts, such as the famed and sought after Iron Cutlass and the Golden Plague Doctor mask. ";
  document.querySelector("#p6").textContent =
    "Cliff: The cliff was a very popular tourist site where tourists can sightsee and hike. At the very bottom of the cliff, there was a young sakura tree. When the wind blew, its petals traveled across the site, giving its blessings to the tourists. There were shops with popular street snacks and souvenirs, there was even a place for you to rest. The melody from the wind chimes added to the festival mood. At the top of the cliff you would enjoy a light breeze with the smell of the sea. People would go there at all times of the day, and night. The sunset and sunrise are very beautiful sights. The gentle sound of waves crashing against the rocks creates a romantic atmosphere  as the sun rises.";
});
